const items = [
  {
    id: 0,
    name: "Umbrella",
    price: 5.0,
    source: require("../assets/umbrella.jpeg"),
    like: false,
  },
  {
    id: 1,
    name: "Paper Bag",
    price: 2.0,
    source: require("../assets/paper_bag.jpg"),
    like: false,
  },
  {
    id: 2,
    name: "Watermelon",
    price: 1.5,
    source: require("../assets/watermelon.jpeg"),
    like: false,
  },
  {
    id: 3,
    name: "Tuning Fork",
    price: 10,
    source: require("../assets/tuning_fork.jpeg"),
    like: false,
  },
  {
    id: 4,
    name: "Shirt",
    price: 15.0,
    source: require("../assets/shirt.jpeg"),
    like: false,
  },
  {
    id: 5,
    name: "Tie",
    price: 8.0,
    source: require("../assets/tie.jpeg"),
    like: false,
  },
  {
    id: 6,
    name: "Triangle",
    price: 3.5,
    source: require("../assets/triangle.jpeg"),
    like: false,
  },
  {
    id: 7,
    name: "Envelop",
    price: 1.5,
    source: require("../assets/envelop.jpg"),
    like: false,
  },
  {
    id: 8,
    name: "Spatula",
    price: 10.0,
    source: require("../assets/spatula.jpeg"),
    like: false,
  },
  {
    id: 9,
    name: "Kitchen Roller",
    price: 7.0,
    source: require("../assets/kitchen_roller.jpg"),
    like: false,
  },
  {
    id: 10,
    name: "Bread",
    price: 2.5,
    source: require("../assets/toast_bread.jpeg"),
    like: false,
  },
  {
    id: 11,
    name: "Pancake",
    price: 2.0,
    source: require("../assets/pancake.jpg"),
    like: false,
  },
];
export default items;
